# !/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on: Tue 22 Nov 2022 18:26:29
Description: Merge PPIHP output to feature file that can be used by protspace3D
Usage:       python merge_pphip.py

@author: tsenoner
"""
import argparse
from pathlib import Path

def setup_arguments() -> argparse.Namespace:
    """Defines and parses required and optional arguments for the script"""
    parser = argparse.ArgumentParser(
        description="Merge & reshape PPIHP output to a single CSV file"
    )

    # Required argument
    parser.add_argument(
        "-pp",
        "--ppihp_dir",
        required=True,
        type=str,
        help="Path to PPIHP output dir, generated by the `microscope` script",
    )

    args = parser.parse_args()
    colabfold_dir = Path(args.colabfold)
    return colabfold_dir


def main():
    args = setup_arguments()


if __name__ == "__main__":
    main()
